spring.datasource.url=jdbc:postgresql://localhost:5432/ServiTareas
spring.datasource.username=postgres
spring.datasource.password=QeuT#wro4932nd

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
